# Generated by Django 3.2.9 on 2021-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mindicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField(max_length=30)),
            ],
        ),
    ]
